### ISSUE TITLE
Test case 9

### ISSUE THREAD

**Issue by davidvictorgabriel** [Waqar-107/Codeforces#1]
Hello! The test cases aren't working on my account for this problem. could you help me by sending me the test case no 9? Thanks.

**Comment by Waqar-107** [comment]
which problem?

**Comment by davidvictorgabriel** [comment]
http://codeforces.com/problemset/problem/600/B.     If you could send me all the test cases i ll be grateful. Thanks,

**Comment by Waqar-107** [comment]
Sorry, i don't have any test cases, actually in that round you won't be able to see any test cases even if you solve it nor you can see anyone's solution.  If you are using binary search according to the editorial, you may find this helpful, https://pastebin.com/PjPkvpSQ

**Comment by Waqar-107** [comment]
i was stuck in the binary search approach, and used this case
5 4
1 1 1 2 1
1 1 2 2

the answer is-  4 4 5 5

**Comment by davidvictorgabriel** [comment]
I am using two sorted arrays and two pointers. Now i get a wrong answer at question 15, your example case is working. Thanks,
