### ISSUE TITLE
codeforces-987B

### ISSUE THREAD

**Issue by jatinkumar158** [Waqar-107/Codeforces#2]
Hey friend, If I remove the condition
if(x==y)
{
    cout<<"=";
    return 0;
}

The code is not working.And what is the usage of this condition as we are comparing again in the end.

**Comment by jatinkumar158** [comment]
Don't you think this condition is redundant.

**Comment by Waqar-107** [comment]
Hi!
`double a=y*log10(x);
    double b=x*log10(y);`
should be enough to check the conditions, isn't it? but somehow(maybe precision problem) it is not working when x==y, so i handled it before anything. Now for cases like x=2,y=4 i had to check again if a==b. I submitted the problem using python once more without redundant checks and it passed http://codeforces.com/contest/987/submission/38971694

**Comment by jatinkumar158** [comment]
Got it bro...!!!
